In [17]:
#Importing Liberaries
import pandas as pd
import numpy as np

In [18]:
#1-Removing Duplicates

data={'Names': ['Mohammed','Ali','Mohammed','Ali'] , 'Age':[19,18,19,19],
      'Gender':['male','female','male','female']}
df=pd.DataFrame(data)
print('Initial Data:')
display(df)
print("============="*2)
df_cleaned=df.drop_duplicates()
print("Data after Cleaning:")
display(df_cleaned)

#using keep parameter
df_cleaned=df.drop_duplicates(keep='last',)
print("data keeping last")
display(df_cleaned)

#Inplace parameter
print("the usage of inplace parameter")
display(df.drop_duplicates( inplace=False))
display(df)

#subest parameter
print ("the usage of subest parameter")
df_cleaned=df.drop_duplicates(subset='Age')
display(df_cleaned)

Initial Data:

      Names  Age  Gender
0  Mohammed   19    male
1       Ali   18  female
2  Mohammed   19    male
3       Ali   19  female

==========================
Data after Cleaning:

      Names  Age  Gender
0  Mohammed   19    male
1       Ali   18  female
3       Ali   19  female

data keeping last

      Names  Age  Gender
1       Ali   18  female
2  Mohammed   19    male
3       Ali   19  female

the usage of inplace parameter

      Names  Age  Gender
0  Mohammed   19    male
1       Ali   18  female
3       Ali   19  female

      Names  Age  Gender
0  Mohammed   19    male
1       Ali   18  female
2  Mohammed   19    male
3       Ali   19  female

the usage of subest parameter

      Names  Age  Gender
0  Mohammed   19    male
1       Ali   18  female

In [19]:
#2-Handeling Missing Values
#filling
Data={'Name':['Mohammed',None,'Walter White','Raiden']
     ,'Age':[19,18,42,None]
     ,'Place':['Menof','Menof','Albequrqy',None]}
df=pd.DataFrame(Data)
display(df)
df['Name'].fillna('Unknown',inplace=True)
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Place'].fillna('Undefined',inplace=True)
df

           Name   Age      Place
0      Mohammed  19.0      Menof
1          None  18.0      Menof
2  Walter White  42.0  Albequrqy
3        Raiden   NaN       None

C:\Users\mzsho\AppData\Local\Temp\ipykernel_9700\3202013433.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Name'].fillna('Unknown',inplace=True)
C:\Users\mzsho\AppData\Local\Temp\ipykernel_9700\3202013433.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)
C:\Users\mzsho\AppData\Local\Temp\ipykernel_9700\3202013433.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Place'].fillna('Undefined',inplace=True)

           Name        Age      Place
0      Mohammed  19.000000      Menof
1       Unknown  18.000000      Menof
2  Walter White  42.000000  Albequrqy
3        Raiden  26.333333  Undefined

In [20]:
# 2 - drop Missing Values
data = {
    'Name': ['Ali', 'Sara', 'Omar', 'Nada', np.nan],
    'Age': [25, 30, np.nan, 22, 28],
    'Gender': ['M', 'F', 'M', np.nan, 'F'],
    'Salary': [5000, 6000, 5500, 5200, np.nan],
    'Department': ['HR', 'IT', 'HR', 'IT', 'Finance']
}
df=pd.DataFrame(data)
display(df)
df.dropna(inplace=False) #keep Original
display(df)
df.dropna(inplace=True) #Delete Original
display(df)

   Name   Age Gender  Salary Department
0   Ali  25.0      M  5000.0         HR
1  Sara  30.0      F  6000.0         IT
2  Omar   NaN      M  5500.0         HR
3  Nada  22.0    NaN  5200.0         IT
4   NaN  28.0      F     NaN    Finance

   Name   Age Gender  Salary Department
0   Ali  25.0      M  5000.0         HR
1  Sara  30.0      F  6000.0         IT
2  Omar   NaN      M  5500.0         HR
3  Nada  22.0    NaN  5200.0         IT
4   NaN  28.0      F     NaN    Finance

   Name   Age Gender  Salary Department
0   Ali  25.0      M  5000.0         HR
1  Sara  30.0      F  6000.0         IT

In [21]:
#3-Correct DataTypes
data = {'Date': ['2023-01-01', '2023-02-01', '2023-03-01'], 'Sales': [100, 150, 200]} 
df=pd.DataFrame(data)
display(df)
display(df.dtypes)
df['Date'] = pd.to_datetime(df['Date']) 
display(df.dtypes)

         Date  Sales
0  2023-01-01    100
1  2023-02-01    150
2  2023-03-01    200

Date     object
Sales     int64
dtype: object

Date     datetime64[ns]
Sales             int64
dtype: object

In [22]:
#4-Standardize Data
data = {'Name': ['alice', 'BOB', 'Charlie'], 'Age': [25, 30, 35]}
df=pd.DataFrame(data)
display(df)
df['Name']=df['Name'].str.title()
display(df)

      Name  Age
0    alice   25
1      BOB   30
2  Charlie   35

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [23]:
#5-Filter Outliers 
data = {'Values': [10, 12, 1000, 13]}
df=pd.DataFrame(data)
print("\033[31mOriginal DataFrame\033[0m")
display(df) 
Q1=df['Values'].quantile(0.25)
Q3=df['Values'].quantile(0.75)
IQR=Q3-Q1
lower_whisker=Q1-1.5*IQR
upper_whisker=Q3+1.5*IQR
df_cleaned=df[(df['Values']>=lower_whisker) & (df['Values']<=upper_whisker)]
display(df_cleaned)

Original DataFrame

   Values
0      10
1      12
2    1000
3      13

   Values
0      10
1      12
3      13

In [24]:
#6-Normalize Data
data = {'Feature1': [100, 200, 300, 500], 'Feature2': [0.5, 0.2, 0.3,.9]}
df=pd.DataFrame(data)
display(df)
df_Normalized=(df-df.min())/(df.max()-df.min())
display(df_Normalized)

   Feature1  Feature2
0       100       0.5
1       200       0.2
2       300       0.3
3       500       0.9

   Feature1  Feature2
0      0.00  0.428571
1      0.25  0.000000
2      0.50  0.142857
3      1.00  1.000000

In [25]:
data = {
    'Name': ['Ali', 'Sara', 'Omar', 'Nada', np.nan],
    'Age': [25, 30, np.nan, 22, 28],
    'Gender': ['M', 'F', 'M', np.nan, 'F'],
    'Salary': [5000, 6000, 5500, 5200, np.nan],
    'Department': ['HR', 'IT', 'HR', 'IT', 'Finance']}
df=pd.DataFrame(data)
display(df)
df_normalized=df
df_normalized['Age']=(df['Age']-df['Age'].min())/(df['Age'].max()-df['Age'].min())
df_normalized['Salary']=(df['Salary']-df['Salary'].min())/(df['Salary'].max()-df['Salary'].min())
display(df_normalized)

   Name   Age Gender  Salary Department
0   Ali  25.0      M  5000.0         HR
1  Sara  30.0      F  6000.0         IT
2  Omar   NaN      M  5500.0         HR
3  Nada  22.0    NaN  5200.0         IT
4   NaN  28.0      F     NaN    Finance

   Name    Age Gender  Salary Department
0   Ali  0.375      M     0.0         HR
1  Sara  1.000      F     1.0         IT
2  Omar    NaN      M     0.5         HR
3  Nada  0.000    NaN     0.2         IT
4   NaN  0.750      F     NaN    Finance

In [26]:
#7. Remove Irrelevant Data
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35], 'Unnecessary': [1, 2, 3]}
df=pd.DataFrame(data)
display(df)
df_cleaned=df.drop(columns=['Unnecessary'])
display(df_cleaned)

      Name  Age  Unnecessary
0    Alice   25            1
1      Bob   30            2
2  Charlie   35            3

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [27]:
#8. Validate Data Integrity
data = {'Name': ['Alice', 'Bob', 'Charly'], 'Age': [25, 30, 35]}
valid_names = ['Alice', 'Bob', 'Charlie']
df = pd.DataFrame(data)
display(df)
df_cleaned=df[df['Name'].isin(valid_names)]
display(df_cleaned)

     Name  Age
0   Alice   25
1     Bob   30
2  Charly   35

    Name  Age
0  Alice   25
1    Bob   30

In [28]:
#9. Document Cleaning Steps
data = {'Name': ['Alice', 'Bob', 'Charlie', 'Alice'], 'Age': [25, 30, 35, np.nan], 'Salary': [50000, 60000, 75000, 50000]} 
df=pd.DataFrame(data)
display(df)
cleaning_steps=[]
df_cleaned=df.drop_duplicates(subset=['Name'])
cleaning_steps.append('Removed Duplicate rows')
display(df_cleaned)
df_cleaned['Age']=df_cleaned['Age'].astype(int)
df_cleaned['Age']=df_cleaned['Age'].astype(int)
cleaning_steps.append('datatypes corrected')
display(df_cleaned.dtypes)

      Name   Age  Salary
0    Alice  25.0   50000
1      Bob  30.0   60000
2  Charlie  35.0   75000
3    Alice   NaN   50000

      Name   Age  Salary
0    Alice  25.0   50000
1      Bob  30.0   60000
2  Charlie  35.0   75000

C:\Users\mzsho\AppData\Local\Temp\ipykernel_9700\74588936.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Age']=df_cleaned['Age'].astype(int)
C:\Users\mzsho\AppData\Local\Temp\ipykernel_9700\74588936.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Age']=df_cleaned['Age'].astype(int)

Name      object
Age        int32
Salary     int64
dtype: object

In [29]:
#11.1.Label encoding
data = {
    'Name': ['Ali', 'Sara', 'Omar', 'Nada', np.nan],
    'Age': [25, 30, np.nan, 22, 28],
    'Gender': ['M', 'F', 'M', np.nan, 'F'],
    'Salary': [5000, 6000, 5500, 5200, np.nan],
    'Department': ['HR', 'IT', 'HR', 'IT', 'Finance']
}
df=pd.DataFrame(data)
df['Gender'].fillna(value='unknown',inplace=True)
df['Gender_encoded']=df['Gender'].map({'M':1,'F':0,'unknown':-1})
df

C:\Users\mzsho\AppData\Local\Temp\ipykernel_9700\2925538540.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].fillna(value='unknown',inplace=True)

   Name   Age   Gender  Salary Department  Gender_encoded
0   Ali  25.0        M  5000.0         HR               1
1  Sara  30.0        F  6000.0         IT               0
2  Omar   NaN        M  5500.0         HR               1
3  Nada  22.0  unknown  5200.0         IT              -1
4   NaN  28.0        F     NaN    Finance               0

In [30]:
#label encoding using sklearn
df=df.drop(columns='Gender_encoded')
display(df)
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Gender_encoded'] = encoder.fit_transform(df['Gender'])
print(df)

   Name   Age   Gender  Salary Department
0   Ali  25.0        M  5000.0         HR
1  Sara  30.0        F  6000.0         IT
2  Omar   NaN        M  5500.0         HR
3  Nada  22.0  unknown  5200.0         IT
4   NaN  28.0        F     NaN    Finance

   Name   Age   Gender  Salary Department  Gender_encoded
0   Ali  25.0        M  5000.0         HR               1
1  Sara  30.0        F  6000.0         IT               0
2  Omar   NaN        M  5500.0         HR               1
3  Nada  22.0  unknown  5200.0         IT               2
4   NaN  28.0        F     NaN    Finance               0

In [31]:
df=df.drop(columns='Gender_encoded')
display(df)
df=pd.get_dummies(df,columns=['Gender'])
display(df)

   Name   Age   Gender  Salary Department
0   Ali  25.0        M  5000.0         HR
1  Sara  30.0        F  6000.0         IT
2  Omar   NaN        M  5500.0         HR
3  Nada  22.0  unknown  5200.0         IT
4   NaN  28.0        F     NaN    Finance

   Name   Age  Salary Department  Gender_F  Gender_M  Gender_unknown
0   Ali  25.0  5000.0         HR     False      True           False
1  Sara  30.0  6000.0         IT      True     False           False
2  Omar   NaN  5500.0         HR     False      True           False
3  Nada  22.0  5200.0         IT     False     False            True
4   NaN  28.0     NaN    Finance      True     False           False

In [32]:
df=pd.get_dummies(df,columns=['Department'],drop_first=True)
df

,Name,Age,Salary,Gender_F,Gender_M,Gender_unknown,Department_HR,Department_IT
0,Ali,25.0,5000.0,False,True,False,True,False
1,Sara,30.0,6000.0,True,False,False,False,True
2,Omar,NaN,5500.0,False,True,False,True,False
3,Nada,22.0,5200.0,False,False,True,False,True
4,NaN,28.0,NaN,True,False,False,False,False